#!/bin/bash
# Implements: DIARY-OPS-single-promotable-artifact/D
# Generate (default) or --check the controlled mobile environment delta record.
# Reads the authoritative per-flavor sources, fails on any undeclared per-flavor
# key, and emits a committed markdown record enumerating the entire delta.
#
# Requires Bash 4+ (uses `declare -A` for associative arrays). macOS ships Bash
# 3.2; install a modern bash via `brew install bash` and run as
# `/opt/homebrew/bin/bash tool/generate_env_delta_record.sh ...`. CI's ubuntu
# runner has Bash 5 so the gate works there unconditionally.
if [ "${BASH_VERSINFO[0]:-0}" -lt 4 ]; then
  printf 'ERROR: %s requires Bash 4+; this is bash %s.\n' \
    "$0" "${BASH_VERSION:-unknown}" >&2
  printf 'On macOS, run: brew install bash && /opt/homebrew/bin/bash %s "$@"\n' "$0" >&2
  exit 1
fi
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(git -C "$APP_DIR" rev-parse --show-toplevel)"

# Sources of truth (overridable for tests).
FLAVORIZR="${CDIARY_FLAVORIZR:-$APP_DIR/android/app/flavorizr.gradle.kts}"
FASTFILE="${CDIARY_FASTFILE:-$APP_DIR/ios/fastlane/Fastfile}"
SRC_DIR="${CDIARY_SRC_DIR:-$APP_DIR/android/app/src}"
RECORD="${CDIARY_RECORD:-$REPO_ROOT/_reports/reference/mobile-env-delta.md}"

ENVS=(dev qa uat prod)
MODE="generate"
[ "${1:-}" = "--check" ] && MODE="check"

fail() { printf 'ERROR: %b\n' "$*" >&2; exit 1; }

# --- Allowlist scan: flavorizr flavor blocks ---------------------------------
# Allowed per-flavor keys: dimension, applicationId, resValue(app_name).
undeclared="$(awk '
  /create\(/ { inblock=1; next }
  inblock && /^[[:space:]]*}/ { inblock=0; next }
  inblock {
    line=$0; gsub(/^[[:space:]]+|[[:space:]]+$/, "", line)
    if (line=="") next
    if (line ~ /^dimension[[:space:]]*=/) next
    if (line ~ /^applicationId[[:space:]]*=/) next
    if (line ~ /^resValue\(.*name[[:space:]]*=[[:space:]]*"app_name"/) next
    print line
  }
' "$FLAVORIZR")"
if [ -n "$undeclared" ]; then
  fail "undeclared per-flavor key(s) in flavorizr.gradle.kts:\n$undeclared"
fi

# --- Allowlist scan: android flavor source sets ------------------------------
# Allowed override files under src/<flavor>/: google-services.json and
# launcher icon overrides (res/mipmap-*/ic_launcher.png).
# The allowlist is intentionally strict: any NEW per-flavor file (e.g. a
# round-icon variant) must be consciously added here and to the record —
# that conscious review is the point of the controlled delta (assertion D).
for env in "${ENVS[@]}"; do
  d="$SRC_DIR/$env"
  [ -d "$d" ] || continue
  extra="$(find "$d" -type f \
    ! -name google-services.json \
    ! -name ic_launcher.png)"
  if [ -n "$extra" ]; then
    fail "undeclared per-flavor file(s) under src/$env:\n$extra"
  fi
done

# --- Extract per-flavor values -----------------------------------------------
declare -A APPID APPNAME GSVC IOSID IOSPROFILE ICON

appid_block="$(awk '/^APP_IDENTIFIERS/{p=1} p{print} p&&/^}$/{exit}' "$FASTFILE")"
profile_block="$(awk '/^PROFILE_NAMES/{p=1} p{print} p&&/^}$/{exit}' "$FASTFILE")"

for env in "${ENVS[@]}"; do
  block="$(awk -v f="$env" \
    '$0 ~ "create\\(\"" f "\"\\)" {p=1} p{print} p&&/^[[:space:]]*}/{exit}' "$FLAVORIZR")"
  APPID[$env]="$(printf '%s\n' "$block" | \
    sed -n 's/.*applicationId[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p')"
  APPNAME[$env]="$(printf '%s\n' "$block" | \
    sed -n 's/.*name[[:space:]]*=[[:space:]]*"app_name"[^"]*value[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p')"
  IOSID[$env]="$(printf '%s\n' "$appid_block" | \
    sed -n "s/.*\"$env\"[[:space:]]*=>[[:space:]]*\"\([^\"]*\)\".*/\1/p")"
  IOSPROFILE[$env]="$(printf '%s\n' "$profile_block" | \
    sed -n "s/.*\"$env\"[[:space:]]*=>[[:space:]]*\"\([^\"]*\)\".*/\1/p")"
  if [ -f "$SRC_DIR/$env/google-services.json" ]; then
    GSVC[$env]="android/app/src/$env/google-services.json"
  else
    GSVC[$env]="android/app/google-services.json (default)"
  fi
  if [ -d "$SRC_DIR/$env/res" ]; then
    ICON[$env]="android/app/src/$env/res/mipmap-*/ic_launcher.png"
  else
    ICON[$env]="android/app/res/mipmap-*/ic_launcher.png (default)"
  fi
done

# --- Validate every dimension resolved for every env -------------------------
for env in "${ENVS[@]}"; do
  [ -n "${APPID[$env]:-}" ]      || fail "no applicationId for '$env' in flavorizr.gradle.kts"
  [ -n "${APPNAME[$env]:-}" ]    || fail "no app_name for '$env' in flavorizr.gradle.kts"
  [ -n "${IOSID[$env]:-}" ]      || fail "no iOS bundle id for '$env' in Fastfile"
  [ -n "${IOSPROFILE[$env]:-}" ] || fail "no iOS provisioning profile for '$env' in Fastfile"
done

# --- Emit the record ---------------------------------------------------------
emit() {
  cat <<EOF
# Mobile Environment Delta Record

<!-- GENERATED by apps/daily-diary/clinical_diary/tool/generate_env_delta_record.sh -->
<!-- Do not edit by hand. Regenerate after changing flavorizr.gradle.kts, the    -->
<!-- Fastlane identifier/profile maps, or per-flavor android source sets.        -->

Implements: DIARY-OPS-single-promotable-artifact/D

Every mobile environment package derives from a single environment-independent
compilation (proven byte-identical by tool/verify_shared_compile.sh). The table
below enumerates the complete set of differences between any two environment
packages. No differences exist other than those listed: the generator fails if
an undeclared per-flavor key appears in flavorizr.gradle.kts or in a per-flavor
android source set.

| Dimension | dev | qa | uat | prod |
| --- | --- | --- | --- | --- |
| env pointer (assets/config/env.json) | dev | qa | uat | prod |
| Android applicationId | ${APPID[dev]} | ${APPID[qa]} | ${APPID[uat]} | ${APPID[prod]} |
| iOS bundle id | ${IOSID[dev]} | ${IOSID[qa]} | ${IOSID[uat]} | ${IOSID[prod]} |
| launcher metadata (app_name) | ${APPNAME[dev]} | ${APPNAME[qa]} | ${APPNAME[uat]} | ${APPNAME[prod]} |
| launcher icon | ${ICON[dev]} | ${ICON[qa]} | ${ICON[uat]} | ${ICON[prod]} |
| native service config | ${GSVC[dev]} | ${GSVC[qa]} | ${GSVC[uat]} | ${GSVC[prod]} |
| iOS provisioning profile | ${IOSPROFILE[dev]} | ${IOSPROFILE[qa]} | ${IOSPROFILE[uat]} | ${IOSPROFILE[prod]} |
| code-signing identity (Doppler config) | dev | qa | uat | prod |
EOF
}

if [ "$MODE" = "check" ]; then
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' EXIT
  emit > "$tmp"
  if ! diff -u "$RECORD" "$tmp"; then
    rm -f "$tmp"
    fail "mobile-env-delta.md is out of date — run tool/generate_env_delta_record.sh and commit the result."
  fi
  rm -f "$tmp"
  echo "OK: mobile env delta record is current and complete."
else
  mkdir -p "$(dirname "$RECORD")"
  emit > "$RECORD"
  echo "Wrote $RECORD"
fi
