#!/usr/bin/env bash
# Implements: DIARY-OPS-single-promotable-artifact/D
# Generate (default) or --check the controlled mobile environment delta record.
#
# Reads the single source of truth (flavorizr.yaml) for per-flavor identity,
# cross-checks the autogenerated Gradle file (flavorizr.gradle.kts) to catch
# yaml-vs-gradle drift, fails on any undeclared per-flavor key in the Gradle
# file, and emits a committed markdown record enumerating the entire delta.
#
# Requires Bash 4+ (associative arrays). macOS ships Bash 3.2 — install via
# `brew install bash` and run as `/opt/homebrew/bin/bash tool/...`. Also
# requires `yq` (mikefarah/yq; `brew install yq`). CI's ubuntu runner has both.
if [ "${BASH_VERSINFO[0]:-0}" -lt 4 ]; then
  printf 'ERROR: %s requires Bash 4+; this is bash %s.\n' \
    "$0" "${BASH_VERSION:-unknown}" >&2
  printf 'On macOS, run: brew install bash && /opt/homebrew/bin/bash %s "$@"\n' "$0" >&2
  exit 1
fi
set -euo pipefail
command -v yq >/dev/null 2>&1 || {
  echo "ERROR: yq not found. Install via 'brew install yq'." >&2
  exit 1
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(git -C "$APP_DIR" rev-parse --show-toplevel)"

# Sources (overridable for tests).
MANIFEST="${CDIARY_MANIFEST:-$APP_DIR/flavorizr.yaml}"
FLAVORIZR_GRADLE="${CDIARY_FLAVORIZR:-$APP_DIR/android/app/flavorizr.gradle.kts}"
SRC_DIR="${CDIARY_SRC_DIR:-$APP_DIR/android/app/src}"
RECORD="${CDIARY_RECORD:-$REPO_ROOT/_reports/reference/mobile-env-delta.md}"

MODE="generate"
[ "${1:-}" = "--check" ] && MODE="check"

fail() { printf 'ERROR: %b\n' "$*" >&2; exit 1; }

# Envs that have a native build config (excludes `local`, which is Dart-only).
# The order is yaml-document order — that's what flows into the delta record's
# column ordering, so adding a new env appends it to the right edge.
mapfile -t ENVS < <(yq -r '.flavors | to_entries | .[] | select(.value.native != false) | .key' "$MANIFEST")

# --- Allowlist scan: flavorizr.gradle.kts flavor blocks ----------------------
# Allowed per-flavor keys: dimension, applicationId, resValue(app_name). Any
# extra hand-injected key in the generated .kts is an unreviewed per-env delta.
undeclared="$(awk '
  /create\(/ { inblock=1; next }
  inblock && /^[[:space:]]*}/ { inblock=0; next }
  inblock {
    line=$0; gsub(/^[[:space:]]+|[[:space:]]+$/, "", line)
    if (line=="") next
    if (line ~ /^dimension[[:space:]]*=/) next
    if (line ~ /^applicationId[[:space:]]*=/) next
    if (line ~ /^resValue\(.*name[[:space:]]*=[[:space:]]*"app_name"/) next
    print line
  }
' "$FLAVORIZR_GRADLE")"
if [ -n "$undeclared" ]; then
  fail "undeclared per-flavor key(s) in flavorizr.gradle.kts:\n$undeclared"
fi

# --- Allowlist scan: android flavor source sets ------------------------------
# Allowed override files under src/<flavor>/: google-services.json and
# launcher icon overrides (res/mipmap-*/ic_launcher.png).
# Strict by design: any NEW per-flavor file (e.g. round-icon variant) must be
# consciously added here and to the record — that conscious review IS the
# controlled-delta gate (assertion D).
for env in "${ENVS[@]}"; do
  d="$SRC_DIR/$env"
  [ -d "$d" ] || continue
  extra="$(find "$d" -type f \
    ! -name google-services.json \
    ! -name ic_launcher.png)"
  if [ -n "$extra" ]; then
    fail "undeclared per-flavor file(s) under src/$env:\n$extra"
  fi
done

# --- Extract per-flavor values from yaml + cross-check Gradle ----------------
declare -A APPID APPNAME IOSID IOSPROFILE GSVC ICON

# Helper: extract one applicationId from a `create("<env>") { ... }` block in
# flavorizr.gradle.kts. Used only to cross-check the yaml; the yaml IS the
# source of truth, this validates the autogenerated .kts didn't drift.
extract_gradle_appid() {
  local env="$1"
  awk -v f="$env" \
    '$0 ~ "create\\(\"" f "\"\\)" {p=1} p{print} p&&/^[[:space:]]*}/{exit}' \
    "$FLAVORIZR_GRADLE" |
    sed -n 's/.*applicationId[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p'
}

for env in "${ENVS[@]}"; do
  APPID[$env]="$(yq -r ".flavors.$env.android.applicationId" "$MANIFEST")"
  APPNAME[$env]="$(yq -r ".flavors.$env.app.name" "$MANIFEST")"
  IOSID[$env]="$(yq -r ".flavors.$env.ios.bundleId" "$MANIFEST")"
  IOSPROFILE[$env]="$(yq -r ".flavors.$env.ios.provisioningProfile" "$MANIFEST")"

  # Cross-check: yaml vs Gradle. If someone hand-edits the .kts without
  # syncing the yaml (or runs flutter_flavorizr with a stale yaml), this
  # fires. The error names the divergence concretely.
  gradle_appid="$(extract_gradle_appid "$env")"
  [ -n "$gradle_appid" ] || fail "flavorizr.gradle.kts has no applicationId for '$env' (yaml says ${APPID[$env]}) — re-run dart run flutter_flavorizr"
  [ "${APPID[$env]}" = "$gradle_appid" ] || \
    fail "flavorizr.yaml says android applicationId for '$env' is '${APPID[$env]}' but flavorizr.gradle.kts says '$gradle_appid' — re-run dart run flutter_flavorizr to resync"

  # google-services + launcher icon: presence-based (file may or may not exist
  # per-flavor; the manifest path is canonical).
  if [ -f "$SRC_DIR/$env/google-services.json" ]; then
    GSVC[$env]="android/app/src/$env/google-services.json"
  else
    GSVC[$env]="android/app/google-services.json (default)"
  fi
  if [ -d "$SRC_DIR/$env/res" ]; then
    ICON[$env]="android/app/src/$env/res/mipmap-*/ic_launcher.png"
  else
    ICON[$env]="android/app/res/mipmap-*/ic_launcher.png (default)"
  fi
done

# --- Validate every dimension resolved for every env -------------------------
for env in "${ENVS[@]}"; do
  [ -n "${APPID[$env]:-}" ]      && [ "${APPID[$env]}" != "null" ]      || fail "no android.applicationId for '$env' in flavorizr.yaml"
  [ -n "${APPNAME[$env]:-}" ]    && [ "${APPNAME[$env]}" != "null" ]    || fail "no app.name for '$env' in flavorizr.yaml"
  [ -n "${IOSID[$env]:-}" ]      && [ "${IOSID[$env]}" != "null" ]      || fail "no ios.bundleId for '$env' in flavorizr.yaml"
  [ -n "${IOSPROFILE[$env]:-}" ] && [ "${IOSPROFILE[$env]}" != "null" ] || fail "no ios.provisioningProfile for '$env' in flavorizr.yaml"
done

# --- Emit the record ---------------------------------------------------------
# Builds a markdown table whose columns are the envs in manifest order.
# Adding/removing an env in flavorizr.yaml automatically reshapes the table.
emit_row() {
  local label="$1"; shift
  printf '| %s' "$label"
  for v in "$@"; do printf ' | %s' "$v"; done
  printf ' |\n'
}

# Build helper arrays whose i-th element is the value for ENVS[i].
build_row() {
  local -n arr="$1"   # nameref to associative array
  local row=()
  for env in "${ENVS[@]}"; do row+=("${arr[$env]}"); done
  printf '%s\n' "${row[@]}"
}

emit() {
  cat <<EOF
# Mobile Environment Delta Record

<!-- GENERATED by apps/daily-diary/clinical_diary/tool/generate_env_delta_record.sh -->
<!-- Do not edit by hand. The source of truth is apps/daily-diary/clinical_diary/  -->
<!-- flavorizr.yaml; this script reads it (and cross-checks the autogenerated     -->
<!-- flavorizr.gradle.kts). Regenerate after adding/removing flavors or changing  -->
<!-- per-flavor android source sets.                                               -->

Implements: DIARY-OPS-single-promotable-artifact/D

Every mobile environment package derives from a single environment-independent
compilation (proven byte-identical by tool/verify_shared_compile.sh). The table
below enumerates the complete set of differences between any two environment
packages. No differences exist other than those listed: the generator fails if
the yaml manifest disagrees with the generated flavorizr.gradle.kts, or if an
undeclared per-flavor key appears in either.

EOF
  # Header row + separator.
  emit_row "Dimension" "${ENVS[@]}"
  local sep=("---")
  for _ in "${ENVS[@]}"; do sep+=("---"); done
  printf '|'; for s in "${sep[@]}"; do printf ' %s |' "$s"; done; printf '\n'

  # Data rows.
  emit_row "env pointer (assets/config/env.json)" "${ENVS[@]}"

  local row=()
  for env in "${ENVS[@]}"; do row+=("${APPID[$env]}"); done
  emit_row "Android applicationId" "${row[@]}"

  row=(); for env in "${ENVS[@]}"; do row+=("${IOSID[$env]}");      done; emit_row "iOS bundle id"               "${row[@]}"
  row=(); for env in "${ENVS[@]}"; do row+=("${APPNAME[$env]}");    done; emit_row "launcher metadata (app_name)" "${row[@]}"
  row=(); for env in "${ENVS[@]}"; do row+=("${ICON[$env]}");       done; emit_row "launcher icon"               "${row[@]}"
  row=(); for env in "${ENVS[@]}"; do row+=("${GSVC[$env]}");       done; emit_row "native service config"       "${row[@]}"
  row=(); for env in "${ENVS[@]}"; do row+=("${IOSPROFILE[$env]}"); done; emit_row "iOS provisioning profile"    "${row[@]}"
  emit_row "code-signing identity (Doppler config)" "${ENVS[@]}"
}

if [ "$MODE" = "check" ]; then
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' EXIT
  emit > "$tmp"
  if ! diff -u "$RECORD" "$tmp"; then
    rm -f "$tmp"
    fail "mobile-env-delta.md is out of date — run tool/generate_env_delta_record.sh and commit the result."
  fi
  rm -f "$tmp"
  echo "OK: mobile env delta record is current and complete."
else
  mkdir -p "$(dirname "$RECORD")"
  emit > "$RECORD"
  echo "Wrote $RECORD"
fi
