#!/bin/bash
# Check if Claude is in the correct worktree
# Returns status and instructions

set -e

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo "")
if [ -z "$REPO_ROOT" ]; then
  echo "ERROR: Not in a git repository"
  exit 1
fi

CONFIG_FILE="$REPO_ROOT/untracked-notes/agent-ops.json"

# Check if agent-ops is initialized
if [ ! -f "$CONFIG_FILE" ]; then
  echo "STATUS: not_initialized"
  echo "MESSAGE: Agent-ops not initialized."
  echo "ACTION: Run ./agent-ops/scripts/init-agent.sh"
  exit 0
fi

# Read config
AGENT_NAME=$(jq -r '.agent_name' "$CONFIG_FILE")
PRODUCT_WORKTREE=$(jq -r '.product_worktree_path' "$CONFIG_FILE")
CURRENT_DIR=$(pwd)

# Check if product worktree exists
if [ ! -d "$PRODUCT_WORKTREE" ]; then
  echo "STATUS: worktree_missing"
  echo "MESSAGE: Product worktree not created yet."
  echo "AGENT_NAME: $AGENT_NAME"
  echo "ACTION: Run ./agent-ops/scripts/init-agent.sh to create worktrees"
  exit 0
fi

# Check if we're in the product worktree
if [ "$CURRENT_DIR" == "$PRODUCT_WORKTREE" ]; then
  echo "STATUS: ready"
  echo "MESSAGE: Hi, I'm agent $AGENT_NAME. Ready to work."
  echo "AGENT_NAME: $AGENT_NAME"
  echo "WORKTREE: $PRODUCT_WORKTREE"
  exit 0
else
  # Create terminal switching script for next shell
  PRODUCT_BRANCH=$(jq -r '.product_branch' "$CONFIG_FILE")

  cat > "$HOME/claude_agent_terminal.sh" <<EOF
#!/bin/bash
# Auto-generated by agent-ops check-worktree.sh
# This script switches to the product worktree for agent: $AGENT_NAME

cd "$PRODUCT_WORKTREE" || {
  echo "Error: Cannot change to product worktree: $PRODUCT_WORKTREE"
  exit 1
}

echo "════════════════════════════════════════════════════════════"
echo "✓ Switched to agent $AGENT_NAME product worktree"
echo "  Directory: $PRODUCT_WORKTREE"
echo "  Branch: $PRODUCT_BRANCH"
echo ""
echo "⚠️  To start Claude Code, run: claude"
echo "════════════════════════════════════════════════════════════"
EOF

  chmod +x "$HOME/claude_agent_terminal.sh"

  echo "STATUS: wrong_location"
  echo "MESSAGE: I'm agent $AGENT_NAME, but I'm not in my worktree."
  echo "AGENT_NAME: $AGENT_NAME"
  echo "CURRENT_DIR: $CURRENT_DIR"
  echo "EXPECTED_DIR: $PRODUCT_WORKTREE"
  echo "ACTION: Open a NEW terminal (will auto-switch) OR manually run: cd $PRODUCT_WORKTREE"
  exit 0
fi
