#!/bin/bash
# Initialize agent configuration for this session
# Run once per session - generates agent name and creates TWO worktrees

set -e

# Get product branch
PRODUCT_BRANCH=$(git branch --show-current)

# Extract session ID from product branch (pattern: digits followed by letters)
SESSION_ID=$(echo "$PRODUCT_BRANCH" | grep -oP '\d+[A-Za-z]+$' || echo "")

if [ -z "$SESSION_ID" ]; then
  # No session ID in branch name - generate one from branch name hash
  echo "No session ID found in branch: $PRODUCT_BRANCH"
  echo "Generating session ID from branch name..."
  BRANCH_HASH=$(echo -n "$PRODUCT_BRANCH" | md5sum | grep -oP '^[0-9a-f]+')
  SESSION_ID="${BRANCH_HASH:0:6}"  # Use first 6 hex chars as session ID
  echo "Generated session ID: $SESSION_ID"
fi

# Generate deterministic agent name
NAMES=(anvil axle bearing bellows bolt cam clamp clutch crank drill flywheel forge fulcrum gear hammer hinge hoist jack lathe lever motor piston pulley pump ratchet rivet rotor saw spindle spring sprocket turbine valve vise wedge wheel winch wrench)
HASH=$(echo -n "$SESSION_ID" | md5sum | grep -oP '^[0-9a-f]+')
INDEX=$((0x${HASH:0:8} % ${#NAMES[@]}))
AGENT_NAME=${NAMES[$INDEX]}

# Define paths
REPO_ROOT=$(git rev-parse --show-toplevel)
CONFIG_FILE="$REPO_ROOT/untracked-notes/agent-ops.json"
WORKTREES_DIR="$(dirname "$REPO_ROOT")/$(basename "$REPO_ROOT")-worktrees"
AGENT_BRANCH="claude/$AGENT_NAME"

# Both worktrees in same container directory with clear naming
# Pattern: /parent/repo-worktrees/agent_name and /parent/repo-worktrees/agent_name-ops
AGENT_WORKTREE_PATH="$WORKTREES_DIR/$AGENT_NAME-ops"
PRODUCT_WORKTREE_PATH="$WORKTREES_DIR/$AGENT_NAME"

# Ensure directories exist
mkdir -p "$REPO_ROOT/untracked-notes"
mkdir -p "$WORKTREES_DIR"

# Check if config already exists
if [ -f "$CONFIG_FILE" ]; then
  EXISTING_NAME=$(jq -r '.agent_name' "$CONFIG_FILE" 2>/dev/null || echo "")
  if [ "$EXISTING_NAME" == "$AGENT_NAME" ]; then
    echo "Agent already initialized: $AGENT_NAME"
    echo "Config: $CONFIG_FILE"

    # Check if worktrees exist
    if [ -d "$AGENT_WORKTREE_PATH" ] && [ -d "$PRODUCT_WORKTREE_PATH" ]; then
      echo ""
      echo "✓ Both worktrees already exist"
      echo "  Agent worktree: $AGENT_WORKTREE_PATH"
      echo "  Product worktree: $PRODUCT_WORKTREE_PATH"
      echo ""
      echo "⚠️  To start working, restart Claude from:"
      echo "    cd $PRODUCT_WORKTREE_PATH"
      exit 0
    fi
    # If worktrees don't exist, fall through to create them
  else
    echo "Warning: Existing agent config found with different name: $EXISTING_NAME"
    echo "Overwriting with new agent: $AGENT_NAME"
  fi
fi

echo "Initializing agent: $AGENT_NAME"
echo ""

# Register agent-ops agents in .claude/agents.json
echo "Registering agent-ops agents..."
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
"$SCRIPT_DIR/register-agents.sh"
echo ""

# Create agent coordination worktree (for ai-coordination sub-agent)
if [ ! -d "$AGENT_WORKTREE_PATH" ]; then
  echo "Creating agent coordination worktree..."

  # Check if agent branch exists
  if git show-ref --verify --quiet "refs/heads/$AGENT_BRANCH"; then
    echo "  Branch $AGENT_BRANCH already exists"
  else
    echo "  Creating branch: $AGENT_BRANCH"
    git branch "$AGENT_BRANCH"
  fi

  echo "  Adding worktree: $AGENT_WORKTREE_PATH"
  git worktree add "$AGENT_WORKTREE_PATH" "$AGENT_BRANCH"
  echo "  ✓ Agent coordination worktree created"
else
  echo "✓ Agent coordination worktree already exists: $AGENT_WORKTREE_PATH"
fi

echo ""

# Create product work worktree (for Claude to work in)
if [ ! -d "$PRODUCT_WORKTREE_PATH" ]; then
  echo "Creating product work worktree..."
  echo "  Adding worktree: $PRODUCT_WORKTREE_PATH"
  echo "  Branch: $PRODUCT_BRANCH"
  git worktree add "$PRODUCT_WORKTREE_PATH" "$PRODUCT_BRANCH"
  echo "  ✓ Product work worktree created"
else
  echo "✓ Product work worktree already exists: $PRODUCT_WORKTREE_PATH"
fi

echo ""

# Write config file
cat > "$CONFIG_FILE" <<EOF
{
  "agent_name": "$AGENT_NAME",
  "agent_branch": "$AGENT_BRANCH",
  "agent_worktree_path": "$AGENT_WORKTREE_PATH",
  "product_worktree_path": "$PRODUCT_WORKTREE_PATH",
  "product_branch": "$PRODUCT_BRANCH",
  "session_id": "$SESSION_ID",
  "initialized_at": "$(date -Iseconds)"
}
EOF

echo "✓ Agent initialized: $AGENT_NAME"
echo "  Config: $CONFIG_FILE"
echo "  Agent branch: $AGENT_BRANCH"
echo "  Agent worktree: $AGENT_WORKTREE_PATH"
echo "  Product worktree: $PRODUCT_WORKTREE_PATH"
echo ""

# Create terminal switching script for automatic worktree switching
cat > "$HOME/claude_agent_terminal.sh" <<EOF
#!/bin/bash
# Auto-generated by agent-ops init-agent.sh
# This script switches to the product worktree for agent: $AGENT_NAME

cd "$PRODUCT_WORKTREE_PATH" || {
  echo "Error: Cannot change to product worktree: $PRODUCT_WORKTREE_PATH"
  exit 1
}

echo "════════════════════════════════════════════════════════════"
echo "✓ Switched to agent $AGENT_NAME product worktree"
echo "  Directory: $PRODUCT_WORKTREE_PATH"
echo "  Branch: $PRODUCT_BRANCH"
echo ""
echo "⚠️  To start Claude Code, run: claude"
echo "════════════════════════════════════════════════════════════"
EOF

chmod +x "$HOME/claude_agent_terminal.sh"

echo "════════════════════════════════════════════════════════════"
echo "⚠️  NEXT STEPS:"
echo ""
echo "1. Open a NEW terminal (this will auto-switch to worktree)"
echo "2. Run: claude"
echo ""
echo "Or manually switch now:"
echo "    cd $PRODUCT_WORKTREE_PATH"
echo "════════════════════════════════════════════════════════════"
