import java.util.Properties
import java.io.FileInputStream

plugins {
    id("com.android.application")
    // START: FlutterFire Configuration
    id("com.google.gms.google-services")
    // END: FlutterFire Configuration
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

// Load key.properties for release signing
val keystorePropertiesFile = rootProject.file("key.properties")
val keystoreProperties = Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(FileInputStream(keystorePropertiesFile))
}

// ---------------------------------------------------------------------------
// FIREBASE TEST LAB FIX: resolve strict-version constraint conflicts
//
// The Flutter Gradle plugin and Google Services plugin each add
// `strictly` version constraints on the following test libraries at older
// versions (e.g. junit:4.12, androidx.test:runner:1.2.0). When our
// androidTest dependencies declare newer versions, Gradle rejects the
// resolution and fails at :app:checkQaDebugAndroidTestAarMetadata.
//
// `force(...)` overrides any `strictly` constraint for that coordinate so
// Gradle always resolves to the single version we declare below. This
// affects only the androidTest runtime classpath; release/debug classpaths
// do not include these artifacts at all.
// ---------------------------------------------------------------------------
configurations.all {
    resolutionStrategy {
        force("junit:junit:4.13.2")
        force("androidx.test:runner:1.7.0")
        force("androidx.test:rules:1.7.0")
        force("androidx.test.espresso:espresso-core:3.7.0")
        // Required so Flutter integration_test screenshots (binding.takeScreenshot)
        // can be written through the AndroidX Test Storage Service that Firebase
        // Test Lab enables via useTestStorageService=true, then pulled as evidence.
        force("androidx.test:core:1.6.1")
        force("androidx.test.services:test-services:1.5.0")
    }
}

android {
    namespace = "org.curehht.clinical_diary"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        // Required by flutter_local_notifications (java.time APIs need desugaring
        // on older Android API levels). See its README "Gradle setup".
        isCoreLibraryDesugaringEnabled = true
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "org.curehht.clinical_diary"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName

        // Required by Flutter integration_test and Firebase Test Lab.
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        create("release") {
            keyAlias = keystoreProperties["keyAlias"] as String?
            keyPassword = keystoreProperties["keyPassword"] as String?
            storeFile = keystoreProperties["storeFile"]?.let { file(it) }
            storePassword = keystoreProperties["storePassword"] as String?
        }
    }

    buildTypes {
        release {
            signingConfig = if (keystorePropertiesFile.exists()) {
                signingConfigs.getByName("release")
            } else {
                signingConfigs.getByName("debug")
            }
        }
    }
}

flutter {
    source = "../.."
}

dependencies {
    // Core library desugaring runtime for flutter_local_notifications.
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")

    // Flutter integration_test bridge used by Firebase Test Lab instrumentation.
    // Versions here must match the force() constraints above.
    androidTestImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test:runner:1.7.0")
    androidTestImplementation("androidx.test:rules:1.7.0")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.7.0")
    // Test Storage Service: lets integration_test screenshots be written to the
    // on-device test storage that Firebase Test Lab (useTestStorageService=true)
    // collects, so snapshots are produced alongside the recorded video.
    androidTestImplementation("androidx.test:core:1.6.1")
    androidTestUtil("androidx.test.services:test-services:1.5.0")
}
// ----- BEGIN flavorDimensions (autogenerated by flutter_flavorizr) -----
apply { from("flavorizr.gradle.kts") }
// ----- END flavorDimensions (autogenerated by flutter_flavorizr) -----
