#!/bin/bash
# Create complete plugin directory structure

set -e

# Parse arguments
PLUGIN_NAME=""
MARKETPLACE_PATH=""
AGENT_PATH=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --plugin-name=*)
      PLUGIN_NAME="${1#*=}"
      shift
      ;;
    --marketplace-path=*)
      MARKETPLACE_PATH="${1#*=}"
      shift
      ;;
    --agent-path=*)
      AGENT_PATH="${1#*=}"
      shift
      ;;
    *)
      echo "ERROR: Unknown argument: $1" >&2
      echo "Usage: create-scaffold.sh --plugin-name=NAME --marketplace-path=PATH --agent-path=PATH" >&2
      exit 1
      ;;
  esac
done

# Validate required arguments
if [ -z "$PLUGIN_NAME" ]; then
  echo "ERROR: --plugin-name required" >&2
  exit 1
fi

if [ -z "$MARKETPLACE_PATH" ]; then
  echo "ERROR: --marketplace-path required" >&2
  exit 1
fi

if [ -z "$AGENT_PATH" ]; then
  echo "ERROR: --agent-path required" >&2
  exit 1
fi

# Validate marketplace exists
if [ ! -d "$MARKETPLACE_PATH" ]; then
  echo "ERROR: Marketplace directory not found: $MARKETPLACE_PATH" >&2
  exit 1
fi

# Validate agent file exists
if [ ! -f "$AGENT_PATH" ]; then
  echo "ERROR: Agent file not found: $AGENT_PATH" >&2
  exit 1
fi

# Create plugin directory
PLUGIN_DIR="$MARKETPLACE_PATH/plugins/$PLUGIN_NAME"

if [ -d "$PLUGIN_DIR" ]; then
  echo "ERROR: Plugin already exists: $PLUGIN_DIR" >&2
  echo "" >&2
  echo "Options:" >&2
  echo "1. Use different plugin name" >&2
  echo "2. Delete existing plugin first" >&2
  exit 1
fi

echo "Creating plugin directory structure at: $PLUGIN_DIR"

# Create directories
mkdir -p "$PLUGIN_DIR"/{.claude-plugin,agents,commands,skills,scripts,tests,hooks}

# Copy agent file
AGENT_FILENAME=$(basename "$AGENT_PATH")
cp "$AGENT_PATH" "$PLUGIN_DIR/agents/$AGENT_FILENAME"
echo "Copied agent: agents/$AGENT_FILENAME"

# Create basic plugin.json (will be enhanced by other scripts)
cat > "$PLUGIN_DIR/.claude-plugin/plugin.json" <<EOF
{
  "name": "$PLUGIN_NAME",
  "version": "1.0.0",
  "description": "Generated plugin from agent definition",
  "author": {
    "name": "Generated by plugin-wizard",
    "email": "plugins@anspar.org"
  },
  "agents": [
    {
      "type": "file",
      "path": "agents/$AGENT_FILENAME",
      "model": "haiku"
    }
  ],
  "commands": [],
  "skills": [],
  "hooks": {},
  "metadata": {
    "generated": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
    "generator": "plugin-wizard",
    "keywords": [],
    "documentation": "README.md"
  }
}
EOF

echo "Created .claude-plugin/plugin.json"

# Create basic test runner
cat > "$PLUGIN_DIR/tests/test.sh" <<'EOF'
#!/bin/bash
# Basic test runner for plugin

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

echo "Running plugin tests..."

# Test that plugin.json is valid JSON
echo -n "  Validating plugin.json... "
if jq empty "$PLUGIN_ROOT/.claude-plugin/plugin.json" 2>/dev/null; then
  echo -e "${GREEN}PASS${NC}"
else
  echo -e "${RED}FAIL${NC}"
  exit 1
fi

# Test that agent file exists
echo -n "  Checking agent file... "
AGENT_PATH=$(jq -r '.agents[0].path' "$PLUGIN_ROOT/.claude-plugin/plugin.json")
if [ -f "$PLUGIN_ROOT/$AGENT_PATH" ]; then
  echo -e "${GREEN}PASS${NC}"
else
  echo -e "${RED}FAIL${NC}"
  exit 1
fi

# Test that all skills exist
echo -n "  Checking skills... "
SKILLS_COUNT=$(jq '.skills | length' "$PLUGIN_ROOT/.claude-plugin/plugin.json")
if [ "$SKILLS_COUNT" -gt 0 ]; then
  ALL_EXIST=true
  for skill in $(jq -r '.skills[].path' "$PLUGIN_ROOT/.claude-plugin/plugin.json"); do
    if [ ! -f "$PLUGIN_ROOT/$skill" ]; then
      ALL_EXIST=false
      echo -e "${RED}FAIL${NC}"
      echo "  Missing: $skill"
      exit 1
    fi
  done
  if $ALL_EXIST; then
    echo -e "${GREEN}PASS${NC}"
  fi
else
  echo "SKIP (no skills defined)"
fi

echo -e "${GREEN}All tests passed!${NC}"
EOF

chmod +x "$PLUGIN_DIR/tests/test.sh"
echo "Created tests/test.sh"

# Create .gitkeep for empty directories
touch "$PLUGIN_DIR/commands/.gitkeep"
touch "$PLUGIN_DIR/skills/.gitkeep"
touch "$PLUGIN_DIR/scripts/.gitkeep"
touch "$PLUGIN_DIR/hooks/.gitkeep"

echo ""
echo "Plugin scaffold created successfully at: $PLUGIN_DIR"
echo ""
echo "Directory structure:"
echo "  .claude-plugin/plugin.json"
echo "  agents/$AGENT_FILENAME"
echo "  commands/"
echo "  skills/"
echo "  scripts/"
echo "  hooks/"
echo "  tests/test.sh"
