// IMPLEMENTS REQUIREMENTS:
//   REQ-d00005: Sponsor Configuration Detection Implementation

/// Flavor configuration for the Clinical Diary app.
///
/// This file defines the flavor-specific settings. All configuration
/// (API endpoints, feature flags) is derived from the flavor name.
///
/// Usage:
///   # For web builds (--flavor doesn't work on web):
///   flutter run -d chrome --dart-define=APP_FLAVOR=dev
///
///   # For mobile builds (both work, --flavor sets FLUTTER_APP_FLAVOR):
///   flutter run --flavor dev --dart-define=APP_FLAVOR=dev
///
/// The app reads APP_FLAVOR (or FLUTTER_APP_FLAVOR on mobile) in main.dart
/// and uses FlavorConfig to derive all other settings (apiBase, etc.).
///
/// See also:
/// - lib/main.dart - Flavor initialization
/// - lib/config/app_config.dart - App configuration (uses FlavorConfig)
/// - .idea/runConfigurations/ - IntelliJ IDEA configurations
/// - .vscode/launch.json - VSCode configurations
library;

/// Available app flavors/environments.
enum Flavor { local, dev, qa, uat, prod }

/// Flavor accessor class generated by flutter_flavorizr.
class F {
  F._();

  static Flavor? _appFlavor;

  static Flavor get appFlavor {
    if (_appFlavor == null) {
      throw StateError(
        'Flavor not set. Ensure F.appFlavor is set in main() before accessing.',
      );
    }
    return _appFlavor!;
  }

  static set appFlavor(Flavor value) => _appFlavor = value;

  static String get name => appFlavor.name;

  static String get title {
    switch (appFlavor) {
      case Flavor.local:
        return 'CureHHT Tracker LOCAL';
      case Flavor.dev:
        return 'CureHHT Tracker DEV';
      case Flavor.qa:
        return 'CureHHT Tracker QA';
      case Flavor.uat:
        return 'CureHHT Tracker';
      case Flavor.prod:
        return 'CureHHT Tracker';
    }
  }

  /// Whether the developer-tools menu section (Export/Import/Feature Flags
  /// + the "Add Example Data" affordance) should be shown. Independent of
  /// `showResetData` — uat hides this section but still surfaces Reset.
  static bool get showDevTools {
    switch (appFlavor) {
      case Flavor.local:
      case Flavor.dev:
      case Flavor.qa:
        return true;
      case Flavor.uat:
      case Flavor.prod:
        return false;
    }
  }

  /// Whether the "Reset All Data" testing affordance should be shown.
  /// Available in local/dev/qa/uat; hidden in prod (Tier 2 GDPR flow
  /// will introduce a production-aware variant — CUR-1315).
  static bool get showResetData {
    switch (appFlavor) {
      case Flavor.local:
      case Flavor.dev:
      case Flavor.qa:
      case Flavor.uat:
        return true;
      case Flavor.prod:
        return false;
    }
  }

  /// Whether the environment banner should be shown.
  static bool get showBanner {
    switch (appFlavor) {
      case Flavor.local:
      case Flavor.dev:
      case Flavor.qa:
        return true;
      case Flavor.uat:
      case Flavor.prod:
        return false;
    }
  }
}

/// Flavor definitions with their dart-define values.
///
/// These are used by build scripts and CI/CD to ensure correct configuration.
class FlavorConfig {
  FlavorConfig._();

  /// Local development flavor configuration.
  /// Targets the diary-server published by deployment/local-stack
  /// (sponsor repo) on http://localhost:8081. Override per-build with
  /// --dart-define=DIARY_API_BASE=... (e.g. http://10.0.2.2:8081 for
  /// the Android emulator). BACKEND_URL is honored for back-compat.
  static const local = FlavorValues(
    name: 'local',
    apiBase: 'http://localhost:8081',
    environment: 'local',
    showDevTools: true,
    showResetData: true,
    showBanner: true,
    sponsorBackends: {'CA': 'http://localhost:8081'},
  );

  /// Development flavor configuration
  static const dev = FlavorValues(
    name: 'dev',
    apiBase: 'https://diary-service-1012274191696.europe-west9.run.app',
    environment: 'dev',
    showDevTools: true,
    showResetData: true,
    showBanner: true,
    sponsorBackends: {
      // Callisto dev Cloud Run
      'CA': 'https://diary-service-1012274191696.europe-west9.run.app',
    },
  );

  /// QA flavor configuration
  static const qa = FlavorValues(
    name: 'qa',
    apiBase: 'https://diary-service-421945483876.europe-west9.run.app',
    environment: 'qa',
    showDevTools: true,
    showResetData: true,
    showBanner: true,
    sponsorBackends: {
      'CA': 'https://diary-service-421945483876.europe-west9.run.app',
    },
  );

  /// UAT flavor configuration
  static const uat = FlavorValues(
    name: 'uat',
    apiBase: 'https://diary-server-768644809588.europe-west9.run.app',
    environment: 'uat',
    showDevTools: false,
    showResetData: true,
    showBanner: false,
    sponsorBackends: {
      'CA': 'https://diary-server-768644809588.europe-west9.run.app',
    },
  );

  /// Production flavor configuration
  static const prod = FlavorValues(
    name: 'prod',
    // TODO: Update when prod environment deployed
    apiBase: 'https://diary-server.europe-west9.run.app',
    environment: 'prod',
    showDevTools: false,
    showResetData: false,
    showBanner: false,
    sponsorBackends: {'CA': 'https://diary-server.europe-west9.run.app'},
  );

  /// Get flavor by name
  static FlavorValues byName(String name) {
    return switch (name.toLowerCase()) {
      'local' => local,
      'dev' => dev,
      'qa' => qa,
      'uat' => uat,
      'prod' => prod,
      _ => dev, // Default to dev
    };
  }

  /// All available flavors
  static const all = [local, dev, qa, uat, prod];
}

/// Immutable flavor configuration values
class FlavorValues {
  const FlavorValues({
    required this.name,
    required this.apiBase,
    required this.environment,
    required this.showDevTools,
    required this.showResetData,
    required this.showBanner,
    required this.sponsorBackends,
  });

  final String name;
  final String apiBase;
  final String environment;
  final bool showDevTools;
  final bool showResetData;
  final bool showBanner;

  /// Sponsor backend URLs mapped by 2-letter code prefix.
  /// E.g., {'CA': 'https://diary-server-xxx.run.app'}
  ///
  /// TODO: Replace with central config service on cure-hht-admin GCP project
  /// so new sponsors can be added without app updates.
  final Map<String, String> sponsorBackends;

  /// Generate dart-define argument for this flavor.
  /// Only APP_FLAVOR is needed - all other config is derived from FlavorConfig.
  String get dartDefine => '--dart-define=APP_FLAVOR=$name';
}
