// Persisted notification record + on-the-wire JSON shape consumed by
// the mobile envelope fetcher. The same class is what the OutboxWriter
// inserts into the `notifications` table (Phase 1B schema), what the
// server returns from /api/v1/notifications/{id}, and what the client
// `EnvelopeFetcher` deserialises.

import 'package:comms/src/notifications/envelope_status.dart';
import 'package:comms/src/notifications/notification_type.dart';

// Implements: DIARY-DEV-push-payload-phi-safety/A — envelope carries opaque ids only
// Implements: DIARY-DEV-inbound-event-on-receipt/A — wire format mobile fetches per receipt
// Implements: DIARY-PRD-notification-behavior/A+B — userVisible drives alert vs. silent split
class Envelope {
  const Envelope({
    required this.notificationId,
    required this.participantId,
    required this.type,
    required this.title,
    required this.payload,
    required this.status,
    required this.createdAt,
    this.body,
    this.userVisible = true,
    this.messageId,
    this.error,
    this.sentAt,
    this.deliveredAt,
  });

  factory Envelope.fromJson(Map<String, dynamic> json) {
    return Envelope(
      notificationId: json['notification_id'] as String,
      participantId: json['participant_id'] as String,
      type: NotificationType.fromWire(json['type'] as String),
      title: json['title'] as String,
      body: json['body'] as String?,
      userVisible: json['user_visible'] as bool? ?? true,
      payload: Map<String, dynamic>.from(
        json['payload'] as Map<dynamic, dynamic>,
      ),
      status: EnvelopeStatus.fromWire(json['status'] as String),
      messageId: json['message_id'] as String?,
      error: json['error'] as String?,
      createdAt: DateTime.parse(json['created_at'] as String).toUtc(),
      sentAt: json['sent_at'] != null
          ? DateTime.parse(json['sent_at'] as String).toUtc()
          : null,
      deliveredAt: json['delivered_at'] != null
          ? DateTime.parse(json['delivered_at'] as String).toUtc()
          : null,
    );
  }

  /// UUID; generated by the writer before insert.
  final String notificationId;

  /// Server-side participant row id (RLS scope key).
  final String participantId;

  final NotificationType type;

  /// Human-readable lock-screen title for [userVisible] envelopes.
  /// Title is stored even for silent envelopes so the audit row has a
  /// description, but it is NOT sent in the FCM payload when
  /// [userVisible] is false.
  final String title;

  /// Optional second line for the lock-screen alert. Not sent for
  /// silent envelopes.
  final String? body;

  /// Drives the APNS priority split downstream (see `FcmMessage.userVisible`).
  /// Defaults to true — the common case is an alert; silent pushes
  /// (e.g. `questionnaire_deleted`) explicitly opt out.
  final bool userVisible;

  /// JSON-able domain payload. Mobile dispatchers route on
  /// `payload.action`, etc. PayloadGuard runs over the serialized form
  /// before insert.
  final Map<String, dynamic> payload;

  final EnvelopeStatus status;

  /// FCM resource name returned on a successful dispatch (e.g.
  /// `projects/cure-hht-admin/messages/0:1700...`). Null until [status]
  /// reaches `sent` or beyond.
  final String? messageId;

  /// Failure reason captured when [status] is `failed`. `'UNREGISTERED'`
  /// is a special value the writer uses to trigger
  /// `OutboxWriter.onUnregistered`.
  final String? error;

  final DateTime createdAt;
  final DateTime? sentAt;
  final DateTime? deliveredAt;

  /// JSON shape used by both the wire format and the Phase 1B DB
  /// columns. Field names are snake_case to match Postgres conventions.
  Map<String, dynamic> toJson() => <String, dynamic>{
    'notification_id': notificationId,
    'participant_id': participantId,
    'type': type.wire,
    'title': title,
    if (body != null) 'body': body,
    'user_visible': userVisible,
    'payload': payload,
    'status': status.wire,
    if (messageId != null) 'message_id': messageId,
    if (error != null) 'error': error,
    'created_at': createdAt.toUtc().toIso8601String(),
    if (sentAt != null) 'sent_at': sentAt!.toUtc().toIso8601String(),
    if (deliveredAt != null)
      'delivered_at': deliveredAt!.toUtc().toIso8601String(),
  };

  /// Returns a copy with one or more fields overridden — used by the
  /// repository to evolve status, messageId, and timestamps without
  /// reconstructing the full payload.
  Envelope copyWith({
    EnvelopeStatus? status,
    String? messageId,
    String? error,
    DateTime? sentAt,
    DateTime? deliveredAt,
  }) {
    return Envelope(
      notificationId: notificationId,
      participantId: participantId,
      type: type,
      title: title,
      body: body,
      userVisible: userVisible,
      payload: payload,
      status: status ?? this.status,
      messageId: messageId ?? this.messageId,
      error: error ?? this.error,
      createdAt: createdAt,
      sentAt: sentAt ?? this.sentAt,
      deliveredAt: deliveredAt ?? this.deliveredAt,
    );
  }
}
